version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase-if-necessary
    # Needed until separate automerge logic in place
    assignees:
      - "Silic0nS0ldier"
